---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mapbot-ingress
  namespace: mapbot
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: wooork.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mapbot-frontend
                port:
                  number: 3000
  tls:
    - hosts:
        - wooork.space
      secretName: mapbot-tls
